### ISSUE TITLE
Creative_Provider does not work

### ISSUE THREAD

**Issue by Badboys9998** [nolimet/DysonSphereMods#1]
does not work??????

**Comment by nolimet** [comment]
Could you provide some extra info?
Also did you follow the easy steps?
1. Place down a splitter
2. Setup some outputs (make sure there are no inputs)
3. Set a filter on one of the outputs

After that you should see items flow out.

Also if you use the thunder store make sure you press launch with mods.
Otherwise you will just start the normal game without mods.

**Comment by Badboys9998** [comment]
this is what you have on the website

How do you do this awesomeness?
Plop down a Splitter
Connect a bunch of outputs (a max of 3)
Set a filter for once of the outputs!
.....
Profit! You got all the stuffs

it don't say this
(make sure there are no inputs)

**Comment by nolimet** [comment]
Yea will update that info on the portal

**Comment by nolimet** [comment]
The info has been updated. Might take a bit for it have fully deployed on there server.

**Comment by Badboys9998** [comment]
it works real good tried it last night
